#服务器端口号
server:
  port: 5200
---
#实现github登录的属性
github:
  client:
    id: 9c7781539c114fa76a78
    secret: a12fee4f6ff4a324649074f6ef2fade87c91860e
  redirect:
    uri: http://localhost:5200/callback
---
#spring基础配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false
  devtools:
    restart:
      emabled: true
---
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itpro.community.pojo
---
#日志配置
logging:
  file:
    name: logs/community.log
    max-history: 5
    max-size: 50MB
  level:
    root: info